### ISSUE TITLE
Problemas al reiniciar keystone

### ISSUE THREAD

**Issue by josedom24** [iesgn/openstack-ubuntu-ansible#3]
<pre>NOTIFIED: [keystoneserver | restart keystone] ********************************* 
failed: [controller] => {"failed": true}

FATAL: all hosts have already failed -- aborting

NOTIFIED: [keystoneserver | restart keystone] ********************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting

FATAL: all hosts have already failed -- aborting

NOTIFIED: [keystoneserver | restart keystone] ********************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jose/site.retry

controller                 : ok=40   changed=31   unreachable=0    failed=1  </pre>

No se si tiene que ver con entos mensajes de syslog:
<pre>
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 InnoDB: Could not open or create data files.
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 InnoDB: If you tried to add new data files, and it failed here,
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 InnoDB: you should now edit innodb_data_file_path in my.cnf back
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 InnoDB: to what it was, and remove the new ibdata files InnoDB created
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 InnoDB: in this failed attempt. InnoDB only wrote those files full of
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 InnoDB: zeros, but did not yet use them in any way. But be careful: do not
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 InnoDB: remove old data files which contain your precious data!
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 [ERROR] Plugin 'InnoDB' init function returned error.
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 [ERROR] Unknown/unsupported storage engine: innodb
Jan  8 15:33:30 vagrant-ubuntu-trusty-64 mysqld: 160108 15:33:30 [ERROR] Aborting
</pre>

**Comment by josedom24** [comment]
Cuando vuelvo a ejecutar el playbook, me da el siguiente error:

<pre>
TASK: [dbserver | update mysql root password for all root accounts] *********** 
failed: [controller] => {"failed": true}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
FATAL: all hosts have already failed -- aborting
</pre>

**Comment by josedom24** [comment]
El error lo da en el paso:

<pre>
TASK: [keystoneserver | DB sync for keystone] ********************************* 
changed: [controller]
NOTIFIED: [keystoneserver | restart keystone] ********************************* 
failed: [controller] => {"failed": true}
</pre>

**Comment by josedom24** [comment]
En al carpeta /root aparece el siguiente fichero, que es un error:

<pre>
-rw-r--r--  1 root root    0 Jan  8 15:54 {failed:
</pre>

**Comment by albertomolina** [comment]
A mí me funciona correctamente, no sé si estará relacionado con la versión de ansible, vagrant o virtualbox utilizadas. Yo estoy utilizando todos paquetes de jessie

**Comment by josedom24** [comment]
Desde el controller cargando las credenciales, no puedo ver los endpoints:

<pre>
# openstack endpoint list
</pre>

¿No es normal? ¿no?

**Comment by albertomolina** [comment]
Sí, es normal si se utiliza fichero.

Para verificarlo prueba:

```
nova endpoints
```

**Comment by albertomolina** [comment]
Related to ansible release used
