### ISSUE TITLE
Reinicio del nodo controlador

### ISSUE THREAD

**Issue by josedom24** [iesgn/openstack-ubuntu-ansible#4]
Al reiniciar el nodo controlador, no se levanta en el orden adecuado el puente openvswitch y por lo tanto hay levantarlo manualmente.

Además se pierde el servidor DNS

**Comment by albertomolina** [comment]
Lo del DNS es cuestión de deinstalar el paquete resolvconf y poner a mano el fichero /etc/network/interfaces o no desinstalarlo y agregar la línea 

dns-nameserver {{ DNS }}

al bloque de br-ex
